background = #1b1b1b
foreground = #d1d0c5
cursor-color = #c5d977
cursor-text = #1b1b1b
selection-background =#2d3e4e
selection-foreground =#d1d0c5
palette = 0=#1b1b1b
palette = 1=#9e3b26
palette = 2=#7da453
palette = 3=#c75c36
palette = 4=#2d3e4e
palette = 5=#9e3b26
palette = 6=#5c5c5c
palette = 7=#d1d0c5
palette = 8=#5c5c5c
palette = 9=#c75c36
palette = 10=#c5d977
palette = 11=#c5d977
palette = 12=#2d3e4e
palette = 13=#c75c36
palette = 14=#7da453
palette = 15=#ffffff
